# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-24 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160130_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='party',
            name='members',
        ),
    ]
